### PR TITLE
Added file uppsercase and lowercase filter documentation

### PR DESCRIPTION
**Pull request by hkulekci**
My english is not very well. Sorry, about that. If this pr is ok, I will try to improve file Encrypt and Decrypt part, too.

### CODE REVIEW

**Comment by hkulekci** [comment]
Ops, I sent pr to master but I don't know which one is correct?

**Comment by samsonasik** [comment]
master is ok I think 👍

**Comment by hkulekci** [comment]
I also add a small addition for file encrypting and decrypting.

**Comment by weierophinney** [comment]
Thanks, @hkulekci

**Pull request merged**
