### PR TITLE
str-function instead of preg-function

### PR DESCRIPTION
**Pull request by freax**
`str_replace` will be much faster

### CODE REVIEW

**Comment by Maks3w** [comment]
@freax Can you provide a benchmark?

**Comment by manuakasam** [comment]
str_replace is faster across the board, assuming I didn't completely f***
up the timing logic ;)

http://3v4l.org/AUfut

Maks3w <notifications@github.com> schrieb am Mo., 15. Juni 2015 um
12:34 Uhr:

**Comment by weierophinney** [comment]
@Maks3w Please merge to develop as well.

**Comment by Maks3w** [comment]
It's merged, bug GH does not display the commit in the PR

**Pull request merged**
