### PR TITLE
Feature service manager v3

### PR DESCRIPTION
**Pull request by macnibblet**

### CODE REVIEW

**Comment by weierophinney** [comment]
@macnibblet Please check the Travis results: https://travis-ci.org/zendframework/zend-filter/jobs/95086990#L388

**Comment by weierophinney** [comment]
Ping @macnibblet — will you have time to investigate this? If not, either myself or @ezimuel will see what we can do. Thanks in advance!

**Comment by macnibblet** [comment]
@weierophinney Fixed.

**Comment by macnibblet** [comment]
:sob:

**Pull request merged**
